# 32 worker x 4 instance = maksimal 128 koneksi klien ke PgBouncer.
<IfModule mpm_prefork_module>
    StartServers 32
    MinSpareServers 16
    MaxSpareServers 32
    MaxRequestWorkers 32
    MaxConnectionsPerChild 0
</IfModule>
