import { Head, useForm } from '@inertiajs/react';
import { Check, ChevronRight, FileKey2, Plus, ShieldCheck } from 'lucide-react';
import { useState } from 'react';

import Heading from '@/components/heading';
import { Badge } from '@apperp/ui/badge';
import { Button } from '@apperp/ui/button';
import { Card, CardAction, CardContent, CardDescription, CardHeader, CardTitle } from '@apperp/ui/card';
import { Checkbox } from '@apperp/ui/checkbox';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from '@apperp/ui/dialog';
import { Field, FieldError, FieldGroup, FieldLegend, FieldSet } from '@apperp/ui/field';
import { Input } from '@apperp/ui/input';

type Permission = { code: string; name: string; app_id: string; entry_point_code: string; access_level: string; entry_point: { code: string; name: string; type: string } | null };
type Privilege = { code: string; name: string; app_id: string | null; source: 'manifest' | 'custom'; status: 'draft' | 'active'; permissions: Pick<Permission, 'code' | 'name' | 'entry_point_code' | 'access_level'>[] };
type Duty = { code: string; name: string; app_id: string | null; source: 'manifest' | 'custom'; status: 'draft' | 'active'; privileges: Pick<Privilege, 'code' | 'name' | 'source' | 'status'>[] };

const toggle = (values: string[], value: string, checked: boolean) => checked ? [...new Set([...values, value])] : values.filter((item) => item !== value);
const State = ({ value }: { value: 'draft' | 'active' }) => <Badge variant={value === 'active' ? 'secondary' : 'outline'}>{value === 'active' ? 'Diterbitkan' : 'Draf'}</Badge>;
function PublishButton({ path }: { path: string }) { const form = useForm({}); return <Button size="sm" variant="outline" disabled={form.processing} onClick={() => form.post(path)}><Check />Terbitkan</Button>; }

function PrivilegeDialog({ permissions }: { permissions: Permission[] }) {
    const [open, setOpen] = useState(false);
    const form = useForm({ name: '', permission_codes: [] as string[] });
    return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button variant="outline"><Plus />Tugas akses</Button></DialogTrigger><DialogContent className="max-h-[calc(100dvh-2rem)] overflow-y-auto"><DialogHeader><DialogTitle>Tugas akses baru</DialogTitle></DialogHeader><form onSubmit={(event) => { event.preventDefault(); form.post('/settings/security-configuration/privileges', { onSuccess: () => setOpen(false) }); }}><FieldGroup><Field><Input label="Nama tugas akses" value={form.data.name} onChange={(event) => form.setData('name', event.target.value)} /><FieldError>{form.errors.name}</FieldError></Field><FieldSet><FieldLegend>Pilih izin yang diperlukan</FieldLegend><div className="max-h-72 space-y-3 overflow-y-auto rounded-md border p-3">{permissions.map((permission) => <label key={permission.code} className="flex items-start gap-3 text-sm"><Checkbox checked={form.data.permission_codes.includes(permission.code)} onCheckedChange={(checked) => form.setData('permission_codes', toggle(form.data.permission_codes, permission.code, checked === true))} /><span><span className="block font-medium">{permission.name}</span><span className="text-xs text-muted-foreground">{permission.entry_point?.name ?? 'Layar atau layanan'} · {permission.access_level}</span></span></label>)}</div><FieldError>{form.errors.permission_codes}</FieldError></FieldSet><Button type="submit" disabled={form.processing}>Simpan sebagai draf</Button></FieldGroup></form></DialogContent></Dialog>;
}

function DutyDialog({ privileges }: { privileges: Privilege[] }) {
    const [open, setOpen] = useState(false);
    const form = useForm({ name: '', privilege_codes: [] as string[] });
    return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button><Plus />Tanggung jawab</Button></DialogTrigger><DialogContent className="max-h-[calc(100dvh-2rem)] overflow-y-auto"><DialogHeader><DialogTitle>Tanggung jawab baru</DialogTitle></DialogHeader><form onSubmit={(event) => { event.preventDefault(); form.post('/settings/security-configuration/duties', { onSuccess: () => setOpen(false) }); }}><FieldGroup><Field><Input label="Nama tanggung jawab" value={form.data.name} onChange={(event) => form.setData('name', event.target.value)} /><FieldError>{form.errors.name}</FieldError></Field><FieldSet><FieldLegend>Pilih tugas akses</FieldLegend><div className="max-h-72 space-y-3 overflow-y-auto rounded-md border p-3">{privileges.map((privilege) => <label key={privilege.code} className="flex items-start gap-3 text-sm"><Checkbox checked={form.data.privilege_codes.includes(privilege.code)} onCheckedChange={(checked) => form.setData('privilege_codes', toggle(form.data.privilege_codes, privilege.code, checked === true))} /><span><span className="block font-medium">{privilege.name}</span><span className="text-xs text-muted-foreground">{privilege.source === 'custom' ? 'Dibuat khusus' : 'Dari aplikasi'} · {privilege.permissions.length} izin</span></span></label>)}</div><FieldError>{form.errors.privilege_codes}</FieldError></FieldSet><Button type="submit" disabled={form.processing}>Simpan sebagai draf</Button></FieldGroup></form></DialogContent></Dialog>;
}

function Tree({ duties, privileges, permissions }: { duties: Duty[]; privileges: Privilege[]; permissions: Permission[] }) {
    const privilegeByCode = new Map(privileges.map((item) => [item.code, item]));
    const permissionByCode = new Map(permissions.map((item) => [item.code, item]));
    return <div className="space-y-3">{duties.map((duty) => <details key={duty.code} className="rounded-md border" open={duty.source === 'custom'}><summary className="flex cursor-pointer list-none items-center gap-3 p-3"><ChevronRight className="size-4 transition-transform group-open:rotate-90" /><ShieldCheck className="size-4 text-primary" /><span className="min-w-0 flex-1 font-medium">{duty.name}</span><State value={duty.status} /><span className="text-xs text-muted-foreground">{duty.source === 'custom' ? 'Dibuat khusus' : 'Dari aplikasi'}</span></summary><div className="space-y-3 border-t p-3 pl-10">{duty.privileges.map((item) => { const privilege = privilegeByCode.get(item.code); return <div key={item.code} className="border-l pl-4"><p className="font-medium text-sm">{item.name}</p><p className="mb-2 text-xs text-muted-foreground">Tugas akses</p>{privilege?.permissions.map((permission) => { const detail = permissionByCode.get(permission.code); return <div className="mb-2 flex items-start gap-2 text-sm" key={permission.code}><FileKey2 className="mt-0.5 size-3.5 text-muted-foreground" /><span><span>{permission.name}</span><span className="block text-xs text-muted-foreground">{detail?.entry_point?.name ?? permission.entry_point_code} · {permission.access_level}</span></span></div>; })}</div>; })}</div></details>)}</div>;
}

export default function SecurityConfiguration({ duties, privileges, permissions }: { duties: Duty[]; privileges: Privilege[]; permissions: Permission[] }) {
    const customPrivileges = privileges.filter((item) => item.source === 'custom');
    const customDuties = duties.filter((item) => item.source === 'custom');
    return <><Head title="Konfigurasi keamanan" /><main className="mx-auto flex w-full max-w-7xl min-w-0 flex-col gap-6 p-6"><Heading title="Konfigurasi keamanan" description="Susun akses aplikasi menjadi tugas akses dan tanggung jawab, lalu gunakan tanggung jawab yang diterbitkan pada role." /><Card><CardHeader><CardTitle>Struktur akses</CardTitle><CardDescription>Bagian dari aplikasi hanya dapat dilihat. Konfigurasi yang dibuat khusus dimulai sebagai draf dan harus diterbitkan sebelum dapat dipilih pada role.</CardDescription><CardAction><div className="flex gap-2"><PrivilegeDialog permissions={permissions} /><DutyDialog privileges={privileges} /></div></CardAction></CardHeader><CardContent><Tree duties={duties} privileges={privileges} permissions={permissions} /></CardContent></Card><div className="grid gap-6 lg:grid-cols-2"><Card><CardHeader><CardTitle>Tugas akses khusus</CardTitle><CardDescription>{customPrivileges.length} tugas dibuat khusus untuk tenant ini.</CardDescription></CardHeader><CardContent>{customPrivileges.length ? <div className="space-y-2">{customPrivileges.map((item) => <div key={item.code} className="flex items-center justify-between gap-3 rounded-md border p-3 text-sm"><span>{item.name}</span><div className="flex items-center gap-2"><State value={item.status} />{item.status === 'draft' && <PublishButton path={`/settings/security-configuration/privileges/${item.code}/publish`} />}</div></div>)}</div> : <p className="text-sm text-muted-foreground">Belum ada tugas akses khusus.</p>}</CardContent></Card><Card><CardHeader><CardTitle>Tanggung jawab khusus</CardTitle><CardDescription>{customDuties.length} tanggung jawab dibuat khusus untuk tenant ini.</CardDescription></CardHeader><CardContent>{customDuties.length ? <div className="space-y-2">{customDuties.map((item) => <div key={item.code} className="flex items-center justify-between gap-3 rounded-md border p-3 text-sm"><span>{item.name}</span><div className="flex items-center gap-2"><State value={item.status} />{item.status === 'draft' && <PublishButton path={`/settings/security-configuration/duties/${item.code}/publish`} />}</div></div>)}</div> : <p className="text-sm text-muted-foreground">Belum ada tanggung jawab khusus.</p>}</CardContent></Card></div></main></>;
}

SecurityConfiguration.layout = { breadcrumbs: [{ title: 'Settings', href: '/settings/access' }, { title: 'Identity & access', href: '/settings/access' }, { title: 'Konfigurasi keamanan', href: '/settings/security-configuration' }] };
